
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 10 17:49:06 COT 2020
//----------------------------------------------------

package Model;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int rightBrace = 23;
  public static final int rightParen = 21;
  public static final int Else = 6;
  public static final int opAdd = 11;
  public static final int For = 9;
  public static final int opDivide = 14;
  public static final int rightBracket = 25;
  public static final int ERROR = 30;
  public static final int opMultiply = 13;
  public static final int stringType = 4;
  public static final int opRelational = 16;
  public static final int leftBracket = 24;
  public static final int Main = 26;
  public static final int Identifier = 28;
  public static final int EOF = 0;
  public static final int opAssignment = 10;
  public static final int Quotes = 2;
  public static final int opAttribution = 17;
  public static final int opSubstract = 12;
  public static final int If = 5;
  public static final int dataType = 3;
  public static final int error = 1;
  public static final int Do = 7;
  public static final int opBoolean = 15;
  public static final int While = 8;
  public static final int semmiColon = 27;
  public static final int opAutoIncrement = 18;
  public static final int leftBrace = 22;
  public static final int leftParen = 20;
  public static final int Number = 29;
  public static final int Boolean = 19;
}

